### ISSUE TITLE
Add eslint and normalize

### ISSUE THREAD

**Issue by chrisjm** [chrisjm/openbrewerydb-gatsby#3]
# Feature request

## Overview

The codebase doesn't currently have a eslint or any linting configuration which will make it difficult to maintain code quality via contribution.

## Tasks

- [x] Set up eslint
- [x] Fix any warnings & errors
- [x] Add Github Actions for linting

## Implementation notes

- Taking most of the eslint rules from Wes Bos's [No-Sweat™ Eslint and Prettier Setup](https://github.com/wesbos/eslint-config-wesbos). I don't want to just extend because I think it will be helpful for others to see the settings and make any suggestions later on.
- There are still some errors and warnings related to emotion and CSS. I think emotion was upgraded to v10 without actually migrating properly. I created a new bug issue to handle this overhaul. See #5
